### PR TITLE
Fix modmenu integration

### LINKED ISSUE #2: Accesses Mod Menu internals instead of using the API
https://github.com/KubeJS-Mods/KubeJS-UI/blob/0747e74a920c2a45125033bdccc9d2387d4f7a51/fabric/src/main/java/dev/latvian/kubejs/ui/fabric/FabricActions.java#L16

This here should use `ModMenuApi.createModsScreen` instead of invoking internal code directly. Also, I would recommend when you do this to update to Mod Menu > 1.15.0 which has a new package name for the API (old one still exists but is deprecated. It seems you haven't updated to a version on the new maven yet, so that is now here: https://maven.terraformersmc.com/com/terraformersmc/modmenu

Make sure to also include
```json
"breaks": {
   "modmenu": "<1.15.0"
}
```
in your fabric.mod.json so people are running an up-to-date mod menu version that has the new API.

### PR DESCRIPTION
**Pull request by MaxNeedsSnacks**
This closes #2 and also hi I'm an idiot

### CODE REVIEW

File: fabric/src/main/java/dev/latvian/kubejs/ui/fabric/FabricActions.java [hunk 1]
```diff
@@ -13,7 +13,7 @@
 	Consumer<Screen> FABRIC_MOD_LIST = screen -> {
 		if (Platform.isModLoaded("modmenu"))
 		{
-			mc().setScreen(new ModsScreen(screen));
+			ModMenuApi.createModsScreen(screen);
```
Comment (Prospector) [inline fabric/src/main/java/dev/latvian/kubejs/ui/fabric/FabricActions.java:16]: I think this is supposed to be mc().setScreen(ModMenuApi.createModsScreen(screen))? It's just creating a screen, but you never set it.

Comment (MaxNeedsSnacks) [reply fabric/src/main/java/dev/latvian/kubejs/ui/fabric/FabricActions.java:16]: ...how do I manage to screw up the simplest of things 😅
